{ config, pkgs, lib, ... }:
{
  options.programs.neovim = {
    options.enable = lib.mkEnableOption "neovim options management in nix";

    options.order = lib.mkOption {
      type = lib.types.int;
      default = 510;
      description = "order in which the import of the generated lua config is added to the init.lua file (lib.mkOrder)";
    };

    options.filename = lib.mkOption {
      type = lib.types.str;
      default = "options";
      description = "filename to use for the generated lua config file";
    };

    options.vim.opt = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      description = "lines of the form vim.opt.<name> = <value> to add to the nvim lua config";
    };

    options.vim.g = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      description = "lines of the form vim.g.<name> = <value> to add to the nvim lua config";
    };
  };

  config.programs.neovim.options.enable = lib.mkDefault (! (config.programs.neovim.options.vim.opt == {}
                                                            && config.programs.neovim.options.vim.g == {}));

  config.xdg.configFile."nvim/lua/${config.programs.neovim.options.filename}.lua".text = let
    vim-opt = lib.attrsToList config.programs.neovim.options.vim.opt;
    vim-g = lib.attrsToList config.programs.neovim.options.vim.g;
    toLua = lib.generators.toLua { multiline = false; };
  in lib.mkIf (config.programs.neovim.options.enable) (
    ''
      -- This file was generated by home-manager from the
      -- `programs.neovim.options` setting. Do not edit manually.

    '' + lib.strings.concatLines (
      (lib.map ({name, value}: ''vim.opt.${name} = ${toLua value}'') vim-opt)
      ++ (lib.map ({name, value}: ''vim.g.${name} = ${toLua value}'') vim-g)
    )
  );

  config.programs.neovim.extraLuaConfig = lib.mkIf (config.programs.neovim.options.enable) (
    lib.mkOrder config.programs.neovim.options.order ''
      require('${config.programs.neovim.options.filename}')
      ''
  );
}
